### ISSUE TITLE
Please check branch fuse62

### ISSUE THREAD

**Issue by weimeilin79** [jbossdemocentral/brms-fuse-integration-demo#10]
Things changed in this branch 

1. Migrate to Fuse 6.2
2. Remove the original fuse project simple Route, it's calling a stock web service, but kicking off a customer evaluation process, make no sense. 
3. Add new project bpmsuite-fuse-integration, read in XML file container customer information, parse this xml file then trigger BPM Process using Camel-CXFRS component (No more Java code), and pass in xml data to the process.
4. Edit BPM custeval process, takes in parameter from beginning. 
5. Edit init.sh add maven check 
6. change documents and diagrams accordingly

**Comment by eschabell** [comment]
Validated and found:

- Small typo in installs/README (last line)

- We need to assign init.bat issue to update for windows to Andrew Blok.

- During install seeing more of the same with other bpms-fuse-travel-agency Fuse 6.2 update:

Installing JBoss FUSE 6.2.0

  - enabling demo accounts logins in users.properties file...

  - making sure 'FUSE' for server is executable...

  - Start up Fuse in the background

  - Create Fabric in Fuse

Logging in as admin
1044 [sshd-SshClient[674b4735]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, e1:cd:63:4a:96:00:90:23:88:46:2d:58:36:2f:6a:48] presented unverified {} key: {}
Error executing command: Cannot obtain service: io.fabric8.api.FabricComplete
  - Testing fabric,retry when not ready
546 [sshd-SshClient[417f6125]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, e1:cd:63:4a:96:00:90:23:88:46:2d:58:36:2f:6a:48] presented unverified {} key: {}
401 [sshd-SshClient[417f6125]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, e1:cd:63:4a:96:00:90:23:88:46:2d:58:36:2f:6a:48] presented unverified {} key: {}
412 [sshd-SshClient[11c2e5bb]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, e1:cd:63:4a:96:00:90:23:88:46:2d:58:36:2f:6a:48] presented unverified {} key: {}
552 [sshd-SshClient[4efaf4ec]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, e1:cd:63:4a:96:00:90:23:88:46:2d:58:36:2f:6a:48] presented unverified {} key: {}
857 [sshd-SshClient[417f6125]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, e1:cd:63:4a:96:00:90:23:88:46:2d:58:36:2f:6a:48] presented unverified {} key: {}
517 [sshd-SshClient[417f6125]-nio2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, e1:cd:63:4a:96:00:90:23:88:46:2d:58:36:2f:6a:48] presented unverified {} key: {}
ERROR, while creating Fabric, please check your Network settings.
Start compile and deploy Fuse and BPM Suite demo project to fuse

It then moves on but it failed to setup stuff and then moves on...

**Comment by weimeilin79** [comment]
1. Correct the XML name and not really sure where the typo is? 
2. Will do after we sort out error No3.

3.
That is weird, because this part in travel agency was not failing in your log, it was the later part that was the problem...  also had this tested by 2 other people but no error like this, I am guessing there are some problem with the network you have so ZooKeeper was not able to setup the Fabric. 

Can you please do a quick test for me, 
by unzipping a Fuse 6.2 and run ./sh to start Fuse Server and start up fabric in fuse console 

type  
```
fabric:create --wait-for-provisioning'
```
Please time this and see how long does it take,  and do a  
```
fabric:status
```
what is the output of this?

then 
Deploy camel route from projects/brms-fuse-integration/bpmsuite-fuse-integration:
 ```
mvn fabric8:deploy
```

**Comment by eschabell** [comment]
Build now works here too... takes a very long time, but works!

1. Time to install (not including login and starting containers):

2. Adjusted init.sh documentation at the end to refer to Containers instead of Runtime tab.

3. Adjusted Readme documentation too for 2 above. Also added new version once merged this branch can be tagged.

4. before we merge needed to have Andrew Block update the init.bat, raised an issue for this so he can do it in the fuse62 branch: 
https://github.com/jbossdemocentral/bpms-fuse-travel-agency-integration-demo/issues/6

After that we can merge this into the master and announce.

**Comment by eschabell** [comment]
Started over with the fuse62 branch, all works during installation, my comments and todo's here:

1. Install takes a bit longer now, timed it on second run with very little maven downloading of deps at: 3m 24s, petty acceptable I think.

2. All screenshots need to be updated to Fuse 6.2.

3. init.bat needs updating by Andrew, added an issue for him to do that:

https://github.com/jbossdemocentral/brms-fuse-integration-demo/issues/11

**Comment by eschabell** [comment]
Looks like all is ready, tested and created pull request #13.
