### ISSUE TITLE
Reference to wrong EAP in Readme.adoc

### ISSUE THREAD

**Issue by PatrickSteiner** [jbossdemocentral/brms-fuse-integration-demo#7]
In the readme you reference the following products to be downloaded and copied

- Boss EAP (jboss-eap-6.4.0.zip)
- BPM Suite (jboss-bpmsuite-6.1.0.GA-installer.jar)
- Fuse (jboss-fuse-full-6.1.1.redhat-412.zip)

The init.sh then tries to find

 - jboss-eap-6.4.0-installer.jar

**Comment by eschabell** [comment]
Good catch... Fixing Monday! 

-- erics (from phone)
