### ISSUE TITLE
Wrong uid/passwd reference in readme.adoc

### ISSUE THREAD

**Issue by PatrickSteiner** [jbossdemocentral/brms-fuse-integration-demo#8]
In the readme the user u:bpmsAdmin/p:bpmsuite1! are referenced, in application-users.properties there is no such user ... only u:erics/p:bpmsuite1!

**Comment by PatrickSteiner** [comment]
Please do not change the docu but the userid/passwd in application-users.properties, as this uid/passwd is also used in the Fuse demo-code!

**Comment by eschabell** [comment]
Will sort it out Monday. ;)

**Comment by eschabell** [comment]
Fixed in https://github.com/jbossdemocentral/brms-fuse-integration-demo/commit/8b80f15f2af33196d640e7b3da8a0ad012ec7a4d
