### ISSUE TITLE
simpleRoute missing authentication?

### ISSUE THREAD

**Issue by PatrickSteiner** [jbossdemocentral/brms-fuse-integration-demo#9]
When following the instructions for local installation, there is the reference to run

mvn camel:run

for a initial simple test.

Maven logs unfortunately show:

[           default-workqueue-1] AuthChallengeProcessor         INFO  basic authentication scheme selected
[           default-workqueue-1] HttpMethodDirector             INFO  Failure authenticating with BASIC 'KIE Workbench Realm'@localhost:8080
Call Restful API again authMethod responseCode:[401] 
Unsuccessful responseCode:[401] theMethod.getResponseBodyAsString():[<html><head><title>JBoss Web/7.5.7.Final-redhat-1 - JBWEB000064: Error report</title><style></style> </head><body><h1>JBWEB000065: HTTP Status 401 - </h1><HR size="1" noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</p><p><b>JBWEB000068: message</b> <u></u></p><p><b>JBWEB000069: description</b> <u>JBWEB000121: This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>JBoss Web/7.5.7.Final-redhat-1</h3></body></html>] urlStr:[http://localhost:8080/business-central/rest/runtime/customer:evaluation:1.0/process/customer.evaluation/start]
newInstanceUrl:[http://localhost:8080/business-central/rest/runtime/customer:evaluation:1.0/process/customer.evaluation/start]

Is this a user, docu or source-code problem?

**Comment by PatrickSteiner** [comment]
This problem is combined with the one with the wrong username/password in BPMS, as the code for the test-client is

public class RestClientSimple {
    ...    
    private static String username = "bpmsAdmin";
    private static String password = "bpmsuite1!";
    ...

While BPM-Suite is installed with "erics/bpmsuite1!" so one or the other needs to be changed!

**Comment by eschabell** [comment]
Fixing Monday too, appreciate the feedback.
